command_timeout = 1000

right_format = """$time"""

[aws]
disabled = true

[os]
disabled = false
[os.symbols]
CentOS = " "
Macos = " "
Linux = " "
Ubuntu = " "
Windows = " "

[python]
python_binary = ["uv-run-python", "python3", "python", "python2"]
# uv-run-python should be like this:
# ```
# #!/usr/bin/env bash
# uv run python "$@"
# ```

[time]
disabled = false
