right_format = """$time"""

[aws]
disabled = true

[os]
disabled = false
[os.symbols]
CentOS = " "
Macos = " "
Linux = " "
Ubuntu = " "
Windows = " "

[python]
python_binary = ["uvx-python", "python3", "python", "python2"]
# uvx-python should be like this:
# ```
# #!/usr/bin/env bash
# uvx python "$@"
# ```

[time]
disabled = false
